# Database Configuration
[database]
host = "ep-holy-forest-141439.us-east-2.aws.neon.tech"
port = 5432
user = "khaledyd"
password = "endykBC26blu"
dbname = "neondb"

# Server Configuration
[server]
port = 8080
